# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build-and-test:
    macos:
      xcode: "11.2.0"
    environment:
      FASTLANE_LANE: scan #custom_lane
    shell: /bin/bash --login -o pipefail
    steps:
      - run:
          name: Create Directory
          command: |
            mkdir -p ~/project/
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
       # Fetch CocoaPods Source
#      - run:
#          name: Fetch CocoaPods Specs
#          command: |
#            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      # Install CocoaPods
      - restore_cache:
          keys:
            - 1-pods-{{ checksum "Podfile.lock" }}
            - 1-pods
      - run:
          name: Install CocoaPods
          command: pod install #--verbose
      - save_cache:
          key: 1-pods-{{ checksum "Podfile.lock" }}
          paths:
            - ./Pods
      # Fastlane
      - run:
          name: Fastlane - build and run tests
          command: fastlane $FASTLANE_LANE
       Artifacts backup
      - store_artifacts:
          path: ~/project/
      - store_test_results:
          path: ~/project/scan

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
